import { Task, User, Project } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex Rivera',
    avatar: 'https://picsum.photos/seed/u1/100/100',
    role: 'Product Designer',
  },
  {
    id: 'u2',
    name: 'Sarah Chen',
    avatar: 'https://picsum.photos/seed/u2/100/100',
    role: 'Senior Developer',
  },
  {
    id: 'u3',
    name: 'Marcus Thorne',
    avatar: 'https://picsum.photos/seed/u3/100/100',
    role: 'QA Engineer',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Nexus Platform',
    key: 'NEX',
    description: 'Core infrastructure for the management tool.',
    ownerId: 'u1',
    members: ['u1', 'u2', 'u3'],
  },
  {
    id: 'p2',
    name: 'Mobile App',
    key: 'MOB',
    description: 'iOS and Android companion apps.',
    ownerId: 'u2',
    members: ['u1', 'u2'],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'NEX-1',
    title: 'Implement OAuth2 Authentication',
    description: 'Setup Google and GitHub authentication providers using Passport.js.',
    status: 'in-progress',
    priority: 'high',
    type: 'feature',
    assigneeId: 'u2',
    dueDate: '2024-03-15',
    createdAt: '2024-02-10',
    storyPoints: 8,
    tags: ['auth', 'backend'],
  },
  {
    id: 'NEX-2',
    title: 'Design System Audit',
    description: 'Review all components for accessibility and consistency.',
    status: 'todo',
    priority: 'medium',
    type: 'task',
    assigneeId: 'u1',
    dueDate: '2024-03-10',
    createdAt: '2024-02-12',
    storyPoints: 5,
    tags: ['design', 'a11y'],
  },
  {
    id: 'NEX-3',
    title: 'Database Migration to PostgreSQL',
    description: 'Move from SQLite to PostgreSQL for production readiness.',
    status: 'backlog',
    priority: 'urgent',
    type: 'feature',
    assigneeId: 'u2',
    dueDate: '2024-03-20',
    createdAt: '2024-02-15',
    storyPoints: 13,
    tags: ['database', 'devops'],
  },
  {
    id: 'NEX-4',
    title: 'API Documentation with Swagger',
    description: 'Generate interactive API docs for the frontend team.',
    status: 'review',
    priority: 'low',
    type: 'task',
    assigneeId: 'u3',
    dueDate: '2024-03-05',
    createdAt: '2024-02-18',
    storyPoints: 3,
    tags: ['docs'],
  },
  {
    id: 'NEX-5',
    title: 'Fix Sidebar Navigation Bug',
    description: 'The sidebar collapses unexpectedly on tablet resolutions.',
    status: 'done',
    priority: 'high',
    type: 'bug',
    assigneeId: 'u1',
    dueDate: '2024-02-25',
    createdAt: '2024-02-20',
    completedAt: '2024-02-24',
    storyPoints: 3,
    tags: ['bug', 'ui'],
  },
  {
    id: 'NEX-6',
    title: 'Memory Leak in Dashboard',
    description: 'Dashboard crashes after 10 minutes of usage.',
    status: 'in-progress',
    priority: 'urgent',
    type: 'bug',
    assigneeId: 'u2',
    dueDate: '2024-03-01',
    createdAt: '2024-02-22',
    storyPoints: 5,
    tags: ['bug', 'performance'],
  },
  {
    id: 'NEX-7',
    title: 'Dark Mode Support',
    description: 'Add dark mode theme using Tailwind CSS.',
    status: 'done',
    priority: 'medium',
    type: 'feature',
    assigneeId: 'u1',
    dueDate: '2024-02-28',
    createdAt: '2024-02-10',
    completedAt: '2024-02-22',
    storyPoints: 8,
    tags: ['ui', 'theme'],
  },
  {
    id: 'NEX-8',
    title: 'Unit Tests for Auth Service',
    description: 'Increase coverage to 90%.',
    status: 'done',
    priority: 'medium',
    type: 'task',
    assigneeId: 'u3',
    dueDate: '2024-02-26',
    createdAt: '2024-02-15',
    completedAt: '2024-02-23',
    storyPoints: 5,
    tags: ['testing'],
  },
  {
    id: 'NEX-9',
    title: 'Mobile Responsiveness Fixes',
    description: 'Fix layout issues on small screens.',
    status: 'review',
    priority: 'medium',
    type: 'bug',
    assigneeId: 'u1',
    dueDate: '2024-03-05',
    createdAt: '2024-02-24',
    storyPoints: 2,
    tags: ['bug', 'ui'],
  },
  {
    id: 'NEX-10',
    title: 'Integrate Stripe Payments',
    description: 'Allow users to subscribe to premium plans.',
    status: 'backlog',
    priority: 'high',
    type: 'feature',
    assigneeId: 'u2',
    dueDate: '2024-04-01',
    createdAt: '2024-02-25',
    storyPoints: 21,
    tags: ['payments', 'feature'],
  },
];
